### PR TITLE
HW3

### PR DESCRIPTION
**Pull request by sauravpdx**
Fullstack HW3

### CODE REVIEW

**Comment by gaurikasar** [comment]
Hi Saurav,

Well written code , I liked the implementation for form.js , just to confirm ,fields for comments and checkbox was also to be added right like shown in the homework3.pdf .

**Comment by vidyav2** [comment]
Good job! Most of it is right.

**Comment by JeremyIV** [comment]
Ex1: You're printing a lot of debugging junk to the console, in the future, please clean this kind of thing up before submitting as final HW version. Visiting your 'cache' page crashes the server. Visiting the check-cookies page when there are no cookies also crashes the server. Please test your solution more thoroughly before submitting. 

Ex2: the two columns appear in reverse order of what is shown in the instructions. Otherwise, looks good.

Ex3: the /submit page doesn't show the status of the feedback textarea or the newsletter checkbox. Also, it's better to use a package to parse the form results, rather than attempting to parse them yourself. Also, you're adding the req.on("end") event handler *inside* of the req.on("data" handler, which is definitely anti-pattern. This on end event handler is added once for each chunk of data received, so that if the server receives multiple chunks, this function will be called multiple times. Not sure what the consequences of this will be, but they won't be good.

**Comment by sauravpdx** [comment]
Thanks for your valuable comments, Jeremy. Will take for all those going forward

**Pull request merged**
